Simple RNN
Ejemplo canónico de una RNN para una tarea más básica, como la predicción de la próxima palabra en una secuencia de texto. Este tipo de tarea ilustra claramente cómo las RNN pueden manejar datos secuenciales.
Importamos los módulos necesarios.

In [ ]:
import tensorflow as tf
import numpy as np

Datos de entrenamiento, es una cadena de texto.

In [ ]:
# fragmento del poema; Nocturno a Rosario
# de Manuel Acuña

text = '¡Pues bien! yo necesito, decirte que te adoro, decirte que te quiero con todo el corazón'

se obtienen todas las palabras de nuestro texto

In [ ]:
words = text.split()
print(words)

['¡Pues', 'bien!', 'yo', 'necesito,', 'decirte', 'que', 'te', 'adoro,', 'decirte', 'que', 'te', 'quiero', 'con', 'todo', 'el', 'corazón']


In [ ]:
# Tokenizacion
word_to_idx = {word: idx for idx, word in enumerate(words)}
idx_to_word = {idx: word for idx, word in enumerate(words)}
print(word_to_idx)
print(idx_to_word)

{'¡Pues': 0, 'bien!': 1, 'yo': 2, 'necesito,': 3, 'decirte': 8, 'que': 9, 'te': 10, 'adoro,': 7, 'quiero': 11, 'con': 12, 'todo': 13, 'el': 14, 'corazón': 15}
{0: '¡Pues', 1: 'bien!', 2: 'yo', 3: 'necesito,', 4: 'decirte', 5: 'que', 6: 'te', 7: 'adoro,', 8: 'decirte', 9: 'que', 10: 'te', 11: 'quiero', 12: 'con', 13: 'todo', 14: 'el', 15: 'corazón'}


Se preparan los datos, en el seq_length ocupamos cierto numero de palabras
lo cual nos ayudara a predecir la siguiente palabra

In [ ]:
seq_length = 6

X = []
y = []
for i in range(len(words) - seq_length):
    seq_in = words[i:i + seq_length]
    seq_out = words[i + seq_length]
    X.append([word_to_idx[word] for word in seq_in])
    y.append(word_to_idx[seq_out])

X = np.array(X)
y = np.array(y)

print(X)
print('*'*10)
print(y)

[[ 0  1  2  3  8  9]
 [ 1  2  3  8  9 10]
 [ 2  3  8  9 10  7]
 [ 3  8  9 10  7  8]
 [ 8  9 10  7  8  9]
 [ 9 10  7  8  9 10]
 [10  7  8  9 10 11]
 [ 7  8  9 10 11 12]
 [ 8  9 10 11 12 13]
 [ 9 10 11 12 13 14]]
**********
[10  7  8  9 10 11 12 13 14 15]


In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(len(words), 10, input_length=seq_length),
    tf.keras.layers.SimpleRNN(32, activation='tanh', input_shape=(seq_length, 10)),
    tf.keras.layers.Dense(len(words), activation='softmax')
])

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

In [ ]:
model.fit(X, y, epochs=50)

Epoch 1/50
1/1 [==============================] - 2s 2s/step - loss: 2.7364
Epoch 2/50
1/1 [==============================] - 0s 15ms/step - loss: 2.7225
Epoch 3/50
1/1 [==============================] - 0s 17ms/step - loss: 2.7084
Epoch 4/50
1/1 [==============================] - 0s 16ms/step - loss: 2.6941
Epoch 5/50
1/1 [==============================] - 0s 11ms/step - loss: 2.6795
Epoch 6/50
1/1 [==============================] - 0s 14ms/step - loss: 2.6645
Epoch 7/50
1/1 [==============================] - 0s 13ms/step - loss: 2.6490
Epoch 8/50
1/1 [==============================] - 0s 13ms/step - loss: 2.6329
Epoch 9/50
1/1 [==============================] - 0s 15ms/step - loss: 2.6163
Epoch 10/50
1/1 [==============================] - 0s 18ms/step - loss: 2.5989
Epoch 11/50
1/1 [==============================] - 0s 17ms/step - loss: 2.5807
Epoch 12/50
1/1 [==============================] - 0s 18ms/step - loss: 2.5617
Epoch 13/50
1/1 [==============================] - 0s 13ms/step

In [ ]:
# Generación de secuencia de palabras
seed_text = '¡Pues bien! yo necesito, decirte que'
seed_words = seed_text.split()
generated_words = list(seed_words)

for _ in range(2):
    x = np.array([[word_to_idx[word] for word in seed_words]])
    y_pred = model.predict(x)
    next_word_idx = np.argmax(y_pred)
    next_word = idx_to_word[next_word_idx]
    generated_words.append(next_word)
    seed_words = seed_words[1:] + [next_word]

generated_text = ' '.join(generated_words)
print(generated_text)


1/1 [==============================] - 0s 34ms/step
¡Pues bien! yo necesito, decirte que te adoro,
